name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  compatibility:
    name: "Compat ${{ matrix.os }}/${{ matrix.toolchain }}/${{ matrix.fdb_feature_version }}"

    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: ["1.85.1", "stable"]
        fdb_feature_version: ["fdb-7_4", "fdb-7_3", "fdb-7_1", "fdb-7_0", "fdb-6_3", "fdb-6_2", "fdb-6_1"]

    runs-on: ${{ matrix.os }}

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.4.3"

      - name: Check FDB library location
        run: "echo skipped-for-baseline-isolation"
      - name: Enable tenant
        run: fdbcli --exec "configure single memory tenant_mode=optional_experimental"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose -p foundationdb --no-default-features --features ${{ matrix.fdb_feature_version }}

      - name: Test
        # Examples needs to have uuid enabled
        run: "echo skipped-for-baseline-isolation"


  test:
    name: "Test foundationDB with ${{ matrix.toolchain }}"
    strategy:
      matrix:
        toolchain: ["1.85.1", "stable", "beta", "nightly"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.4.3"

      - name: Enable tenant
        run: fdbcli --exec "configure single memory tenant_mode=optional_experimental"


      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{ matrix.toolchain }}"
          components: rustfmt, clippy

      - name: Run all tests of foundationdb
        run: "echo skipped-for-baseline-isolation"
      - name: Run all tests of foundationdb with trace feature enabled
        run: "echo skipped-for-baseline-isolation"
      - name: Run all tests of foundationdb-tuple
        run: "echo skipped-for-baseline-isolation"

  lint:
    name: Rustfmt / Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.4.3"

      - name: Enable tenant
        run: fdbcli --exec "configure single memory tenant_mode=optional_experimental"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Fmt
        run: "echo skipped-for-baseline-isolation"

      - name: Clippy
        run: "echo skipped-for-baseline-isolation"

  audit:
    name: Cargo audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.3.0
        with:
          version: "7.1.37"
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
